name = "chem-practice"
pages_build_output_dir = "."
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "chem-db"
database_id = "99927e55-61b3-452c-9a87-3d7d64e6a07c"
